### ISSUE TITLE
ts-stack-filter.js:57 - Source Mapping error

### ISSUE THREAD

**Issue by gatzsche** [SeanSobey/JasmineTSConsoleReporter#1]
Hi Sean,

I have found a bug in `ts-stack-filter.js`.

- line: `57`
- code: `const fileName = path.resolve(srcMapResult.sourcesRelativeTo, originalPosition.source);` 
- input to `path.resolve`:
    - `srcMapResult.sourcesRelativeTo`=`${workspaceFolder}/dist/foo.spec.js.map`
    - `originalPosition.source`=`../src/foo.spec.ts`

- It looks as `path.resolve` treats `foo.spec.js.map` as a folder.
- Thus the following absolute path is generated:
`${workspaceFolder}/dist/foo.spec.js.map/../src/foo.spec.ts`

-  But the right path would be 
`${workspaceFolder}/dist/../src/foo.spec.ts`

- Is there a reason why you are not removing the map file name `foo.spec.js.map` from the path before calculating the absolute path?

Would it be much for you to fix that and provide a new npm?

Let me know if you need more details, e.g. a sample implementation.
Let me know if I shall test a fix.

Best, 
  Gabriel

**Comment by SeanSobey** [comment]
Hi Gabriel,

Thanks for reporting the issue. It was indeed a bug that crept in somehow (probably to my usage of virtual sourcemaps in the project this was split off) and originally it was (and should be) using the `sourcesRelativeTo` directory like you describe.

I have made the fix and published an update :)

Let me know if you experience any more issues.
Sean

**Comment by gatzsche** [comment]
Awesome! I'm going to check it out this evening.
