### ISSUE TITLE
Usage with Karma

### ISSUE THREAD

**Issue by dsnoeck** [SeanSobey/JasmineTSConsoleReporter#3]
Hi, I'm trying to setup it up with Karma by including the helper as explained here: https://github.com/karma-runner/karma-jasmine/issues/189#issuecomment-342578931

Unfortunately I got:  ReferenceError: Can't find variable: require

Any hint about how I could have it to work ?

**Comment by SeanSobey** [comment]
Hi @dsnoeck!

I have not tried this lib with Karma (or even any browser testing actually, just node js so far), and do not have much experience with Karma really.

After a look at the how [karma-jasmine](https://github.com/karma-runner/karma-jasmine) loads Jasmine and the Karma [plugin](https://karma-runner.github.io/2.0/config/plugins.html) docs. I believe this is the issue: This lib is using NodeJS specific module loading, apis and libraries that will not work in the browser context (at least out the box).

That said I believe Karma uses its own reporting system anyway, so even making this lib isomorphic and work in the browser also won't help. So maybe a karma reporter is what you are actually after? Like [karma-remap-coverage](https://www.npmjs.com/package/karma-remap-coverage)?

**Comment by webmaster128** [comment]
I use jasmine tests, JasmineTSConsoleReporter and Karma. The idea is that you use JasmineTSConsoleReporter for command line tests in nodejs and Karma + karma-jasmine (+ e.g karma-jasmine-html-reporter) for the browser testing. This may not give you the same functionality as this lib but you definitely need Karma specific reporters.

**Comment by devrafalko** [comment]
Perhaps you forgot to add the path to your helpers in the `preprocessors` property in the  `karma.conf.js`.


    const webpackConfig = require('./webpack.prod.js');
    module.exports = function(config) {
      config.set({
        files: [
          {pattern: 'src/*.js', watched:false, served:false, included:false, nocache:false},
          {pattern: 'tests/helpers/*.js',watched:false,served:true,included:true},
          {pattern: 'tests/specs/*.js',watched:false,served:true,included:true}
        ],
        webpack: webpackConfig,
        preprocessors: {
          './tests/helpers/*.js': ['webpack'],
          './tests/specs/*.js': ['webpack']
        },
      });
    };

**Comment by dsnoeck** [comment]
Thank you for you suggestion. I'm not working on this task anymore, but I might come back at some point.
